services:
  postgres:
    image: postgres:17
    container_name: sumit-auth-postgres
    
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sumit_auth_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
    name: sumit-auth-postgres-data